"""Pre-discovery clarification questions.

Before launching Phase 1 on a topic-based run, ask the operator 2-4 short
clarifying questions that materially affect channel selection AND can't be
reliably inferred from the description alone (language of source content,
audience level, style preference, regional specificity, etc.).

The questions are generated by Sonnet 4.6 via the same `claude -p` CLI that
`llm.py` uses. The operator answers in a single Telegram message (free-form
text — no per-question parsing); the raw answer is later appended to `pain`
before Phase 1 starts, so it flows through discovery / scoring / compose
naturally without touching any of those signatures.

This is a quality-of-life feature: ANY error here (LLM down, parse fail,
network) must not block Phase 1. We return [] on failure → wizard treats it
as "no clarifications needed" and proceeds normally.
"""

from __future__ import annotations

import json
import logging

from . import llm

log = logging.getLogger("gateway")

# Sonnet 4.6 — picked by operator over Haiku for nuance on niche topics
# (medical / rehab / specialized fitness). Cost is ~$0.01 per call; one call
# per topic per Phase 1 launch is acceptable.
CLARIFY_MODEL = "claude-sonnet-4-6"

SYSTEM_PROMPT = """You are helping a course-onboarding operator decide HOW to search YouTube for a specific online course they want to assemble.

Given a course TOPIC and an optional DESCRIPTION, generate 2-4 SHORT clarifying questions that:
- materially affect channel selection (language, level, style, region, sub-emphasis)
- cannot be reliably inferred from the description the operator already wrote

## Good question topics (ask only when relevant + not already implied)

- Source language: should YouTube channels be in English, Russian, both, or another language?
- Audience experience level: beginners / mixed / advanced / clinicians-only
- Author style / format: solo expert on camera / studio-produced / institution / mix
- Regional or cultural specificity: US methods vs European vs Russian school
- Specific sub-topic to prioritize over others (when the topic has multiple natural angles)
- Specific approaches to AVOID (e.g. "no crossfit-style", "no MLM coaches")

## BAD questions (do not ask)

- Anything already answered in the description — re-asking annoys the operator
- Vague "what do you want?" or "any other preferences?" type questions
- Things not actionable for channel filtering (e.g. course pricing, marketing copy)
- Subjective taste questions ("do you like X?") — ask about constraints, not opinions
- More than 4 questions total

## Rules

- Questions in Russian (the operator answers in Russian)
- Each question 5-15 words, ends with "?"
- Each question on its own — do not combine ("X and Y?") since the operator answers free-form
- Output STRICT JSON only — no prose, no markdown fences, no comments
- Schema:
  {"questions": ["...?", "...?"]}
- If the description is already exhaustive enough that no clarifications would meaningfully change channel selection, return: {"questions": []}

## Examples

Input:
  topic: "Knee rehabilitation after meniscus surgery"
  description: "Anatomy, week-by-week protocol, common mistakes, return to sport"
Good output:
  {"questions": [
    "На каком языке искать каналы — английский, русский или оба?",
    "Какой уровень целевой аудитории — пациенты после операции или физиотерапевты?",
    "Нужны ли только PT-сертифицированные авторы или подходят опытные тренеры?"
  ]}

Input:
  topic: "Fascia release exercises"
  description: ""
Good output:
  {"questions": [
    "На каком языке искать авторов — английский, русский или оба?",
    "Акцент на упрощённые упражнения для новичков или продвинутую самомассажную работу?",
    "Маленькие каналы экспертов или ОК и крупные fitness-каналы?"
  ]}

Input (exhaustive):
  topic: "Daily 10-minute meditation for English-speaking beginners with no prior experience, by certified MBSR teachers only"
  description: "..."
Good output:
  {"questions": []}
"""


def generate_questions(*, topic: str, description: str = "",
                       model: str = CLARIFY_MODEL,
                       timeout: int = 60) -> list[str]:
    """Generate 2-4 short clarifying questions for the operator.

    Returns [] when:
      - topic is empty (nothing to clarify)
      - LLM decides the description is already exhaustive
      - any error occurs (network, parse, CLI failure) — fail-open: wizard
        treats it as "no questions" and proceeds. We must not block Phase 1
        launch on a flaky LLM call here.
    """
    topic = (topic or "").strip()
    if not topic:
        return []

    payload: dict[str, str] = {"topic": topic}
    if description and description.strip():
        payload["description"] = description.strip()
    user = json.dumps(payload, ensure_ascii=False, indent=2)

    try:
        obj = llm._call_json(model=model, system=SYSTEM_PROMPT, user=user,
                             timeout=timeout)
    except Exception as e:
        # Log at WARNING (not ERROR) — this is a soft-fail path, not a bug.
        log.warning(f"clarify.generate_questions: LLM call failed: {e}")
        return []

    if not isinstance(obj, dict):
        log.warning(f"clarify.generate_questions: unexpected response shape: "
                    f"{type(obj).__name__}")
        return []
    qs = obj.get("questions")
    if not isinstance(qs, list):
        log.warning(f"clarify.generate_questions: 'questions' missing or "
                    f"not a list: {qs!r}")
        return []

    # Filter empty strings, strip whitespace, cap at 4.
    out: list[str] = []
    for q in qs:
        s = str(q).strip()
        if s:
            out.append(s)
    return out[:4]


def format_for_pain(questions: list[str], answer: str) -> str:
    """Render a Q&A pair as an extra block to append to `pain` (course
    description) before Phase 1 starts.

    The discovery / scoring / compose prompts already treat `pain` as the
    canonical course specification — appending a structured "OPERATOR
    CLARIFICATIONS" block lets them pick up extra constraints (language,
    style, level) without any new kwarg threading.

    Empty answer → empty string, so caller can safely concat.
    """
    answer = (answer or "").strip()
    if not answer:
        return ""
    if not questions:
        # No questions but operator still provided extra text — keep it.
        return f"\n\n## OPERATOR CLARIFICATIONS\n\n{answer}"

    qa_block = "\n".join(f"- {q}" for q in questions)
    return (
        f"\n\n## OPERATOR CLARIFICATIONS\n\n"
        f"Operator was asked these questions before launching discovery:\n"
        f"{qa_block}\n\n"
        f"Operator's combined free-form answer:\n{answer}"
    )
